// Star Citizen Locations Database - Complete Collection (1,198+ Locations)
// Updated from https://starcitizen.tools/Category:Locations
// Complete list of all Star Citizen universe locations

const locations = [
  // === NUMERICAL & SPECIAL CHARACTERS ===
  "2930-CRU983",
  "78 Leonis (star)",

  // === MAJOR LANDING ZONES & TRADING HUBS ===
  "Aaron Halo",
  "Aberdeen",
  "Abyss",
  "Adir",
  "Adira Falls",
  "Administration Office",
  "Aemilia",
  "Aero",
  "Afterlife",
  "Ail'ka (star)",
  "Ail'ka - Kyuk'ya",
  "Ail'ka - T.āl",
  "Ail'ka - Yā'mon",
  "Ail'ka Belt Alpha",
  "Ail'ka Belt Beta",
  "Akiro Cluster",
  "Ako's Return",
  "Ambitious Dream Station",
  "Angeli",
  "Anóna",
  "ArcCorp Mining Area 022",
  "ArcCorp Mining Area 045",
  "ArcCorp Mining Area 048",
  "ArcCorp Mining Area 056",
  "ArcCorp Mining Area 061",
  "ArcCorp Mining Area 073",
  "ArcCorp Mining Area 141",
  "ArcCorp Mining Area 157",
  "ArcCorp Processing Center 115",
  "ArcCorp Processing Center 123",
  "Area04",
  "Area06",
  "Area11",
  "Area17",
  "Area18",
  "Area20",
  "Aremis",
  "Arial",
  "Arid Reach",
  "Ariel",
  "Armitage (planet)",
  "Ashburn Channel Aid Shelter",
  "Ashana",
  "Ashland",
  "Aston Ridge Aid Shelter",
  "Aspire Grand",
  "Astor's Clearing",
  "Asura",
  "August Dunlow Spaceport",
  "Aydo",

  // === B LOCATIONS ===
  "Bacchus - Garron",
  "Bacchus - Geddon", 
  "Bacchus A",
  "Bacchus B",
  "Bacchus Belt Alpha",
  "Bacchus Flotilla",
  "Bacchus I",
  "Bacchus II",
  "Bacchus III",
  "Baijini Point",
  "Baker - Kiel",
  "Baker - Osiris",
  "Baker - Tayac",
  "Baker - Th.us'ūng",
  "Baker - Yā'mon",
  "Baker A",
  "Baker B",
  "Baker I",
  "Baker II",
  "Baker III",
  "Baker IV",
  "Balto's Blind",
  "Banshee (star)",
  "Banshee - Fora",
  "Banshee - Garron",
  "Banshee - Leir",
  "Banshee - Tamsa",
  "Banshee - Yulin",
  "Banshee I",
  "Banshee II",
  "Banshee IV",
  "Banu Station",
  "Bareton",
  "Barton Flats Aid Shelter",
  "Benny Henge",
  "Benson Mining Outpost",
  "Bevic Convention Center",
  "Blackrock Exchange",
  "Blighter's Run",
  "Bloodshot Ridge",
  "Bloom",
  "Bombora",
  "Boondoggle",
  "Borea",
  "Bountiful Harvest Hydroponics",
  "Branaugh (star)",
  "Branaugh - Chronos",
  "Branaugh Belt Alpha",
  "Branaugh I",
  "Branaugh II", 
  "Branaugh III",
  "Bremen (star)",
  "Bremen - Kallis",
  "Bremen - Nyx",
  "Bremen - Tanga",
  "Bremen - Vega",
  "Bremen I",
  "Bremen III",
  "Bremen IV",
  "Brentworth Care Center (New Babbage)",
  "Brio's Breaker Yard",
  "Broken Moon",
  "Broken Patch",
  "Bruder",
  "Buckets",
  "Bud's Growery",
  "Bueno Ravine",
  "Bullock's Reach",
  "Buloi Sataball Arena",
  "Burnout",

  // === C LOCATIONS ===
  "Café Musain",
  "Calhoun Pass Emergency Shelter",
  "Caliban (star)",
  "Caliban - Nul",
  "Caliban - Oberon",
  "Caliban - Orion", 
  "Caliban - Viking",
  "Caliban 2a",
  "Caliban 3a",
  "Caliban 3b",
  "Caliban 4a",
  "Caliban 4b",
  "Caliban 4c",
  "Caliban 4d",
  "Caliban 4e",
  "Caliban 4f",
  "Caliban Belt Alpha",
  "Caliban I",
  "Caliban III",
  "Caliban IV",
  "Caliban V",
  "Calliope",
  "Callisto",
  "Canard View",
  "Cano (star)",
  "Cano - Davien",
  "Cano - Pyro",
  "Cano Belt Alpha", 
  "Cano I",
  "Cano III",
  "Cano IV",
  "Caplan Circuit",
  "Carteyna",
  "Carteyna City",
  "Carver's Ridge",
  "Cascom",
  "Cassel",
  "Casselean",
  "Castor",
  "Castra (star)",
  "Castra - Hadrian",
  "Castra - Nyx",
  "Castra - Oso",
  "Castra - Oya",
  "Castra - Pyro",
  "Castra I",
  "Cathcart (star)",
  "Cathcart - Davien",
  "Cathcart - Hades",
  "Cathcart - Kilian",
  "Cathcart - Nexus",
  "Cathcart Belt Alpha",
  "Cellin",
  "Centauri (star)",
  "Centauri - Elysium",
  "Centauri - Nul",
  "Centauri Belt Alpha",
  "Centauri I",
  "Centauri IV",
  "Centauri V",
  "Central Business District (Lorville)",
  "Cestulus",
  "Char",
  "Charon (moon)",
  "Charon (star)",
  "Charon - Genesis",
  "Charon - Helios",
  "Charon - Kins",
  "Charon - Tyrol",
  "Chawla's Beach",
  "Checkmate Station",
  "Chronos (star)",
  "Chronos - Branaugh",
  "Chronos - Kellog",
  "Chronos - Kiel",
  "Chronos Belt Alpha",
  "Chronos I",
  "Chronos II",
  "Chronos III",
  "Clear View Emergency Shelter",
  "Cloudrest Retreat",
  "Cloudview Center",
  "Comm Array ST1-02",
  "Comm Array ST1-13",
  "Comm Array ST1-48",
  "Comm Array ST1-61",
  "Comm Array ST1-92",
  "Comm Array ST2-28",
  "Comm Array ST2-47",
  "Comm Array ST2-55",
  "Comm Array ST2-76",
  "Comm Array ST3-18",
  "Comm Array ST3-35",
  "Comm Array ST3-90",
  "Comm Array ST4-22",
  "Comm Array ST4-31",
  "Comm Array ST4-59",
  "Comm Array ST4-64",
  "Connor's",
  "Consumption",
  "Covalex Distribution Centre S1DC06",
  "Covalex Distribution Centre S4DC05",
  "Covalex Hub Gallete",
  "Covalex Hub Gundo",
  "Covalex Hub Lagrange",
  "Covalex Hub Laskowski",
  "Covalex Hub O'Neill",
  "Covalex Hub Reilly",
  "Covalex Hub Sutter",
  "Covalex Hub Tompkins",
  "Covalex Hub Wightman",
  "Covalex Hub Young",
  "Covalex Hub Ziegler",
    "Coven",
  "Cry-Astro Plant CRY-B01",
  "Cry-Astro Plant CRY-B02",
  "Cry-Astro Plant CRY-B11",
  "Cry-Astro Plant CRY-B16",
  "Cygnus",

  // === D LOCATIONS ===
  "Davien (star)",
  "Davien - Cano",
  "Davien - Cathcart",
  "Davien - Sol",
  "Davien - Croshaw",
  "Davien Belt Alpha",
  "Davien I",
  "Davien II",
  "Davien III",
  "Davien IV",
  "Daymar",
  "Deakins Research Outpost",
  "Dell Township",
  "Desmond Memorial Convention Center",
  "Devlin Scrap & Salvage",
  "Dinger's Depot",
  "Dobbs",
  "Downlow",
  "Drifters",
  "Dunboro",
  "Dunlow Ridge Emergency Shelter",
  "Dupree Storage Depot A",
  "Dupree Storage Depot B",
  "Dupree Storage Depot C",
  "Dupree Storage Depot D",
  "Dupree Storage Depot E",
  "Dupree Storage Depot F",
  "Dupree Storage Template",

  // === E LOCATIONS ===
  "Eager Flats Aid Shelter",
  "Eealus (star)",
  "Eealus - La'uo",
  "Eealus - Trise",
  "Ellis (star)",
  "Ellis - Goss",
  "Ellis - Nexus",
  "Ellis - Tayac",
  "Ellis Belt Alpha",
  "Ellis Belt Beta",
  "Ellis I",
  "Ellis II",
  "Ellis III",
  "Ellis IV",
  "Ellis V",
  "Ellis VI",
  "Ellis VII",
  "Ellis VIII",
  "Ellis IX",
  "Ellis X",
  "Ellis XI",
  "Ellis XII",
  "Elsewhere",
  "Elysium (star)",
  "Elysium - Centauri",
  "Elysium - Ferron",
  "Elysium Belt Alpha",
  "Elysium I",
  "Elysium II",
  "Elysium III",
  "Elysium IV",
  "Empyrean Park",
  "Encole Station",
  "Empire Health Services",
  "Europa",
  "Everus Harbor",

  // === F LOCATIONS ===
  "Fallow Field",
  "Farro Data Center Alpha",
  "FEO Canyon Depot",
  "Ferron (star)",
  "Ferron - Elysium",
  "Ferron - Osiris",
  "Ferron Belt Alpha",
  "Ferron I",
  "Ferron II",
  "Ferron III",
  "Ferron IV",
  "Fetch",
  "Finn's Folly",
  "Fora (star)",
  "Fora - Banshee",
  "Fora - Garron",
  "Fora - Hades",
  "Fora - Leir",
  "Fora - Tamsa",
  "Fora Belt Alpha",
  "Fora I",
  "Fora II",
  "Fora III",
  "Frigid Knot",
  "Frostbite (settlement)",

  // === G LOCATIONS ===  
  "G-Loc Bar",
  "Gallete Family Farms",
  "Ganymede",
  "Garron (star)",
  "Garron - Bacchus",
  "Garron - Banshee",
  "Garron - Fora",
  "Garron - Hades",
  "Garron - Kins",
  "Garron - Tyrol",
  "Garron Belt Alpha",
  "Garron I",
  "Garron II",
  "Garron III",
  "Garron IV",
  "Geddon (star)",
  "Geddon - Bacchus",
  "Geddon - Hades",
  "Geddon Belt Alpha",
  "Geddon I",
  "Geddon II",
  "Genesis (star)",
  "Genesis - Charon",
  "Genesis - Hadrian",
  "Genesis Belt Alpha",
  "Genesis I",
  "Genesis II",
  "Ghost Hollow",
  "GIO",
  "Goner's Deal",
  "Gonzo",
  "Good Times Temple",
  "Goss (star)",
  "Goss - Ellis",
  "Goss - Tayac",
  "Goss - Tyrol",
  "Goss Belt Alpha",
  "Goss I",
  "Goss II",
  "Goss III",
  "Grand Barter Bazaar",
  "Gray Gardens",
  "Green Imperial Medical",
  "Greencircle Habitation",
  "Grim HEX",
  "Greycat Pomeroy",
  "Greycat Roc",
  "Greycat Stanton",

  // === H LOCATIONS ===
  "Hades (star)",
  "Hades - Cathcart",
  "Hades - Fora",
  "Hades - Garron",
  "Hades - Geddon",
  "Hades - Kins",
  "Hades - Oberon",
  "Hades - Orion",
  "Hades Belt Alpha",
  "Hades I",
  "Hades II",
  "Hades III",
  "HDMS Chameleon",
  "HDMS Edmond",
  "HDMS Hahn",
  "HDMS Norgay",
  "HDMS Oparei",
  "HDMS Ryder",
  "HDMS Stanhope",
  "HDPC Fissure Pack Station",
  "HDPC Racquel Research Outpost",
  "HDSF Ason",
  "HDSF Stanhope",
  "Hadrian (star)",
  "Hadrian - Castra",
  "Hadrian - Genesis",
  "Hadrian - Oberon",
  "Hadrian Belt Alpha",
  "Hadrian I",
  "Hadrian II",
  "Hadrian III",
  "Half Stack",
  "Hard Knocks",
  "Harper's Point",
  "Hasbin Hall",
  "Haven",
  "Haven Food Cluster",
  "Hela's Regret",
  "Helios (star)",
  "Helios - Charon",
  "Helios - Tyrol",
  "Helios - Vega",
  "Helios Belt Alpha",
  "Helios I",
  "Helios II",
  "Hickes Research Outpost",
  "Hospice",
  "Humboldt Mines",
  "Hurston",
  "Hurston Dynamics Showcase",
  "Hurston Security Station",

  // === I LOCATIONS ===
  "ICC ScanHub Stanton",
  "Independent Arbitrator Hub",
  "Inspiration Park",
  "Intercity Research Facility",
  "Invictus Base",
  "IO",
  "IO-North tower",

  // === J LOCATIONS ===
  "Jackson's Swap",
  "JRPC Alpha Outpost",
  "JRPC Beta Outpost",
  "JRPC Charlie Outpost",
  "JRPC Delta Outpost",
  "JRPC Echo Outpost",
  "JRPC Foxtrot Outpost",
  "JRPC Golf Outpost",
  "JRPC Hotel Outpost",
  "JRPC India Outpost",
  "JRPC Juliet Outpost",
  "JRPC Kilo Outpost",
  "JRPC Lima Outpost",
  "JRPC Mike Outpost",
  "JRPC November Outpost",
  "JRPC Oscar Outpost",
  "JRPC Papa Outpost",
  "JRPC Quebec Outpost",
  "JRPC Romeo Outpost",
  "JRPC Sierra Outpost",
  "JRPC Tango Outpost",
  "JRPC Uniform Outpost",
  "JRPC Victor Outpost",
  "JRPC Whiskey Outpost",
  "JRPC X-ray Outpost",
  "JRPC Yankee Outpost",
  "JRPC Zulu Outpost",
  "Jumptown",
  "JusticeStar Satellite",

  // === K LOCATIONS ===
  "Kabir's Post",
  "Kallis (star)",
  "Kallis - Bremen",
  "Kallis - Nemo",
  "Kallis Belt Alpha",
  "Kallis I",
  "Kallis II",
  "Kant's Peak",
  "Kellog (star)",
  "Kellog - Chronos",
  "Kellog - Virgil",
  "Kellog Belt Alpha",
  "Kellog I",
  "Kellog II",
  "Kellog III",
  "Kelo Bottom",
  "Kiel (star)",
  "Kiel - Baker",
  "Kiel - Chronos",
  "Kiel Belt Alpha",
  "Kiel I",
  "Kiel II",
  "Kiel III",
  "Kiel IV",
  "Kiel V",
  "Kilian (star)",
  "Kilian - Cathcart",
  "Kilian - Nexus",
  "Kilian Belt Alpha",
  "Kilian I",
  "Kilian II",
  "Kinder Plots",
  "Kins (star)",
  "Kins - Charon",
  "Kins - Garron",
  "Kins - Hades",
  "Kins Belt Alpha",
  "Kins I",
  "Kins II",
  "Kudre Ore",
  "Kyuk'ya (star)",
  "Kyuk'ya - Ail'ka",
  "Kyuk'ya Belt Alpha",
    "Kyuk'ya I",

  // === L LOCATIONS ===
  "L19 Residences",
  "La'uo (star)",
  "La'uo - Eealus",
  "La'uo - Tohil",
  "La'uo - Trise",
  "La'uo Belt Alpha",
  "La'uo Belt Beta",
  "Lago",
  "Lagrange Aid Shelter",
  "Lamina OLP",
  "Lamina PAF-I",
  "Lamina PAF-II",
  "Lamina PAF-III",
  "Lanisto",
  "Last Day",
  "Last Ditch",
  "Last Landings",
  "Launch Pad",
  "Lazarus Phoenix Research Lab",
  "Lazarus Tithonus Research Lab",
  "Lazarus Transport Hub Phoenix-I",
  "Lazarus Transport Hub Phoenix-II",
  "Lazarus Transport Hub Phoenix-III",
  "Lazarus Transport Hub Tithonus-I",
  "Lazarus Transport Hub Tithonus-II",
  "Lazarus Transport Hub Tithonus-III",
  "Leavsden Square",
  "Leir (star)",
  "Leir I",
  "Leir III",
  "Levski",
  "List of Stanton locations",
  "Lixāuu",
  "Lo",
  "Locke",
  "Lorona",
  "Lorville",
  "Lorville Outskirts",
  "Lost and Found",
  "Loveridge Mineral Reserve",
  "LROP Rayari Anuk",
  "LROP Rayari Cantwell",
  "LROP Rayari Delta",
  "LROP Rayari Gaines",
  "LROP Rayari Kaltag",
  "LROP Rayari McGrath",
  "Lowdown",
  "Ludlow",
  "Luna",
  "Lyre",
  "Lyria",
  "Lyris Flotilla",
  "Lūng'xyi",

  // === M LOCATIONS ===
  "M.iiy'ong",
  "MacArthur",
  "MacIntyre & Victor's Bar",
  "Magda",
  "Magma",
  "Magnus (star)",
  "Magnus - Stanton",
  "Magnus Gateway",
  "Magnus I",
  "Magnus III",
  "Mainline",
  "Maker's Point",
  "Maria Pure of Heart",
  "Mariana",
  "Marisol Belt",
  "Markahil (star)",
  "Mars",
  "Megumi Refueling",
  "Mentor",
  "Mercury (planet)",
  "Mercy Hospital",
  "MIC-L1 Shallow Frontier Station",
  "MIC-L2 Long Forest Station",
  "MIC-L3 Endless Odyssey Station",
  "MIC-L4 Red Crossroads Station",
  "MIC-L5 Modern Icarus Station",
  "MicroTech (planet)",
  "MicroTech Logistics Depot S4LD01",
  "MicroTech Logistics Depot S4LD13",
  "Mya Aid Shelter",
  "Min 1a",
  "Min 1b",
  "Min 1c",
  "Min 1d",
  "Min I",
  "Miner's Lament",
  "Minlo Spire",
  "Miranda",
  "Mogote Aid Shelter",
  "Monox",
  "Moreland Hills",
  "Moscow",
  "MT DataCenter 2UB-RB9-5",
  "MT DataCenter 4HJ-LVE-A",
  "MT DataCenter 5WQ-R2V-C",
  "MT DataCenter 8FK-Q2X-K",
  "MT DataCenter D79-ECG-R",
  "MT DataCenter E2Q-NSG-Y",
  "MT DataCenter KH3-AAE-L",
  "MT DataCenter L8P-JUC-8 (offline)",
  "MT DataCenter QVX-J88-J",
  "MT DataCenter TMG-XEV-2",
  "MT OpCenter TLI-4",
  "Mya",

  // === N LOCATIONS ===
  "Najita",
  "Nakamura Valley Aid Shelter",
  "Narena's Rest",
  "Nedila",
  "Nemo (star)",
  "Nemo I",
  "Nemo II",
  "Neo Taurii",
  "Neptune",
  "Nest Apartments",
  "Neutrality",
  "Nevermind",
  "New Austin",
  "New Babbage",
  "New Babbage Interstellar Spaceport",
  "New Corvo",
  "New Junction",
  "New York",
  "Newcastle",
  "Nexus (star)",
  "Nexus I",
  "Nexus II",
  "Nexus III",
  "Ne'er",
  "NKZ",
  "Noble",
  "Nogo",
  "NT-999-XV",
  "NT-999-XVI",
  "NT-999-XX",
  "NT-999-XXII",
  "Nuen Waste Management",
  "Nuiqsut Emergency Shelter",
  "Nul (star)",
  "Nul I",
  "Nul II",
  "Nul IV",
  "Nyx (star)",
  "Nyx I",
  "Nyx II",
  "Nyx III",

  // === O LOCATIONS ===
  "OB Heller",
  "OB Kobold",
  "OB Station Gryphon",
  "OB Station Pegasus",
  "Oberon (moon)",
  "Oberon (star)",
  "Oberon III",
  "Oberon IV",
  "Oberon V",
  "Oberon VI",
  "Oberon VII",
  "Odin (star)",
  "Odin II",
  "Odin III",
  "Odin IV",
  "Odyssa",
  "Old '38",
  "Oli'Sha",
  "Olympus",
  "Olympus Pool",
  "OP Station Demien",
  "Operations Depot Lyria",
  "Orbituary",
  "Oretani (star)",
  "Oretani Belt Alpha",
  "Oretani I",
  "Oretani II",
  "Oretani III",
  "Oretani IV",
  "Oretani V",
  "Oretani VI",
  "Orion (star)",
  "Orion Belt Alpha",
  "Orion I",
  "Orion II",
  "Orison",
  "Orison General",
  "Osha",
  "Osiris (star)",
  "Osiris - Baker",
  "Osiris Belt Alpha",
  "Osiris II",
  "Oso (star)",
  "Oso I",
  "Oso II",
  "Oso III",
  "Oso IV",
  "Oso V",
  "Oso VI",
  "Ostler's Claim",
  "Outpost 54",
  "Oya (star)",
  "Oya I",
  "Oya II",
  "Oya III",
  "Oya IV",

  // === SPACE STATIONS & LAGRANGE POINTS ===
  "Port Olisar",
  "Port Renatus", 
  "Port Tressler",
  "Seraphim Station",
  
  // Crusader Lagrange Points
  "CRU-L1",
  "CRU-L4", 
  "CRU-L5",
  "CRU-L1 Ambitious Dream Station",
  "CRU-L4 Shallow Fields Station",
  "CRU-L5 Beautiful Glen Station",
  
  // MicroTech Lagrange Points
  "MIC-L1",
  "MIC-L2",
  "MIC-L3",
  "MIC-L4",
  "MIC-L5",
  
  // ArcCorp Lagrange Points
  "ARC-L1 Wide Forest Station",
  "ARC-L2 Lively Pathway Station", 
  "ARC-L3 Modern Express Station",
  "ARC-L4 Faint Glen Station",
  "ARC-L5 Yellow Core Station",
  
  // Hurston Lagrange Points
  "HUR-L1 Green Glade Station",
  "HUR-L2 Faithful Dream Station",
  "HUR-L3 Thundering Express Station",
  "HUR-L4 Melodic Fields Station",
  "HUR-L5 High Course Station",

  // === P LOCATIONS ===
  "P.uay'aha",
  "Paradise Cove",
  "Patch City",
  "Penselin",
  "Persei",
  "Petram",
  "Petrus",
  "Phobos",
  "Pi'tua",
  "Picker's Field",
  "Pike",
  "Pinecone",
  "Ping'leth",
  "Player hab",
  "Pluto",
  "Point Wain Emergency Shelter",
  "Prime",
  "PRIVATE PROPERTY",
  "Prophet's Peak",
  "Prospect Depot",
  "Prospect Point",
  "Providence industrial platform",
  "Pue'nu",
  "PYAM-SUPVISR-3-4",
  "Pyen'pui.a",
  "Pyro (star)",
  "Pyro - Stanton",
  "Pyro Gateway", 
  "Pyro I",
  "Pyro IV",
  "Pyro V",

  // === Q LOCATIONS ===
  "QuarterDeck",
  "Quasi",
  "Queeg",
  "Quinton",

  // === R LOCATIONS ===
  "R.il'a (star)",
  "R.il'a VI",
  "RAB-Alpha",
  "Rai.p'uāng",
  "Rappel",
  "Rat's Nest",
  "Raven's Roost",
  "Rayari Anvik Research Outpost",
  "Rayari Cantwell Research Outpost",
  "Rayari Deltana Research Outpost",
  "Rayari Kaltag Research Outpost",
  "Rayari Livengood Research Outpost",
  "Rayari McGrath Research Outpost",
  "Razor's Edge",
  "Reclamation & Disposal",
  "Reclamation & Disposal Orinth",
  "Red God",
  "Regiment Downs",
  "Reis",
  "Reisse",
  "Reza's Landing",
  "Rhea",
  "Rhetor (star)",
  "Rhetor I",
  "Rhetor V",
  "Rico's Remains",
  "Riker Memorial Spaceport",
  "Rings of Aremis",
  "Rings of Branaugh II",
  "Rings of Ellis VII",
  "Rings of Kiel V",
  "Rings of Kyuk'ya I",
  "Rings of Neptune",
  "Rings of Saturn",
  "Rings of Tayac II",
  "Rings of Uranus",
  "Rock Bottom",
  "Rod's Fuel 'N Supplies",
  "Rolo's Crater",
  "Rough Landing",
  "Ruin Station",
  "Ruptura OLP",
  "Ruptura PAF-I",
  "Ruptura PAF-II",
  "Ruptura PAF-III",
  "Rustville",
  "RyiXy'an",
  "Rytif",
  "Ryōl",

  // === S LOCATIONS ===
  "S.ap'uāng",
  "Sacren's Plot",
  "Saisei",
  "Sakura Sun Goldenrod Workcenter",
  "Sakura Sun Magnolia Workcenter",
  "Samson & Son's Salvage Center",
  "Saturn",
  "Scarper's Turn",
  "Schwester",
  "Scuttle",
  "Se'kith",
  "Second Sister",
  "Security Post Criska",
  "Security Post Dipur",
  "Security Post Kareah",
  "Security Post Lespin",
  "Security Post Moluto",
  "Security Post Opal",
  "Security Post Prashad",
  "Security Post Thaquray",
  "Security Post Wan",
  "Seer's Canyon",
  "Selene",
  "Serling",
  "Sesen",
  "Severus",
  "Shadowfall",
  "Shady Glen Farms",
  "Shanghai",
  "Shanks",
  "Shepherd",
  "Shepherd's Rest",
  "Sherman",
  "Shoel",
  "Shubin Mining Facility SAL-2",
  "Shubin Mining Facility SAL-5",
  "Shubin Mining Facility SCD-1",
  "Shubin Mining Facility SM0-10",
  "Shubin Mining Facility SM0-13",
  "Shubin Mining Facility SM0-18",
  "Shubin Mining Facility SM0-22",
  "Shubin Mining Facility SMCa-6",
  "Shubin Mining Facility SMCa-8",
  "Shubin Processing Facility SPAL-12",
  "Shubin Processing Facility SPAL-16",
  "Shubin Processing Facility SPAL-21",
  "Shubin Processing Facility SPAL-3",
  "Shubin Processing Facility SPAL-7",
  "Shubin Processing Facility SPAL-9",
  "Shubin Processing Facility SPMC-1",
  "Shubin Processing Facility SPMC-10",
  "Shubin Processing Facility SPMC-11",
  "Shubin Processing Facility SPMC-14",
  "Shubin Processing Facility SPMC-3",
  "Shubin Processing Facility SPMC-5",
  "Sino",
  "Slowburn Depot",
  "Smokestack",
  "Sol (star)",
  "Sol - Croshaw",
  "Sol - Davien",
  "Space Clinics",
  "Space Whale",
  "Spider",
  "Stag's Rut",
  "Stalford",
  "Stanton (star)",
  "Stanton - Magnus",
  "Stanton - Pyro",
  "Stanton - Terra",
  "Stanton Gateway",
  "Starlight Service Station",
  "Stone's Throw",
  "Stonetree",
  "Stratus at Cloudview Center",
  "Sunset Mesa",
  "Supply Gap",
  "Synthworld",

  // === T LOCATIONS ===
  "T.āl (star)",
  "T.āl - Ail'ka",
  "Talarine Divide Aid Shelter",
  "Tamdon Plains Aid Shelter",
  "Tamsa (black hole)",
  "Tamsa I",
  "Tamsa II",
  "Tanga (star)",
  "Tanga Belt Alpha",
  "Tanga I",
  "Tanga II",
  "Tangaroa",
  "Tanys",
  "Taranis (star)",
  "Taranis 2a debris",
  "Taranis Belt Alpha",
  "Taranis Belt Beta",
  "Taranis I",
  "Taranis II",
  "Taranis III",
  "Taranis IV",
  "Tat'Ko",
  "Tayac (star)",
  "Tayac - Baker",
  "Tayac - Goss",
  "Tayac - Terra",
  "Tayac Belt Alpha",
  "Tayac I",
  "Tayac II",
  "TDD Kesner",
  "Teasa Spaceport",
  "Technotic",
  "Teddy's Playhouse",
  "Terminus",
  "Terra",
  "Terra - Stanton",
  "Terra Gateway",
  "Terra Mills HydroFarm",
  "Terra Mills Processing Center",
  "Terra Mills Storage Alpha",
  "Terra Mills Storage Beta",
  "Terra Nova",
  "Test Facility Octagon",
  "Tethle'a",
  "Tethys",
  "Th.us'ūng (star)",
  "Th.us'ūng - Baker",
  "Th.us'ūng Belt Alpha",
  "Th.us'ūng I",
  "The Ark (station)",
  "The Barrens",
  "The Coil",
  "The Dregs",
  "The Factory Line",
  "The Garden",
  "The Golden Riviera",
  "The Grove",
  "The Hollows",
  "The Icebreaker",
  "The Necropolis",
  "The Orphanage",
  "The Pit",
  "The Shades",
  "The Sky Scraper",
  "The Snake Pit",
  "The Yard",
  "Thimblerig",
  "Third Sister",
  "Tiber (star)",
  "Tiber Belt Alpha",
  "Tiber I", 
  "Titan",
  "Titania",
  "Titus",
  "Tobin Expo Center",
  "Tohil (star)",
  "Tohil - La'uo",
  "Tohil - Nyx",
  "Tohil - Oya",
  "Tohil Belt Alpha",
  "Tohil I",
  "Tohil II",
  "Tohil III",
  "Tohil IV",
  "Toja",
  "Tomb",
  "TPF",
  "Tram",
  "Tram & Myers Mining",
  "Tremonte",
  "Trilo",
  "Trise (star)",
  "Trise - Eealus",
  "Trise - La'uo",
  "Trise I",
  "Tyrol - Charon",
  "Tyrol - Goss",
  "Tyrol - Helios",
  "Tyrol A",
  "Tyrol B",
  "Tyrol Belt Alpha",
  "Tyrol I",
  "Tyrol II",
  "Tyrol III",
  "Tyrol IV",
  "Tyrol V",
  "Tyrol VI",
  "Tyrol VII",

  // === U LOCATIONS ===
  "Umbriel",
  "Unnamed abandoned outpost (Cellin)",
  "Unnamed abandoned outpost (Daymar)",
  "Unnamed abandoned outpost (Yela)",
  "Uranus",
  "Uriel",
  "Utopia",

  // === V LOCATIONS ===
  "Vagabond (star)",
  "Vanduul Attack",
  "Vanguard (star)",
  "Vann",
  "Vatra",
  "Vector (star)",
  "Vega (star)",
  "Vega 2A",
  "Vega 2B",
  "Vega Belt Alpha",
  "Vega I",
  "Vega IV",
  "Vendetta (star)",
  "Venus",
  "Veritas (star)",
  "Vermilion (star)",
  "Vesper (star)",
  "Viking (star)",
  "Viking - Caliban",
  "Viking - Orion",
  "Vili",
  "Virgil (star)",
  "Virgil - Kellog",
  "Virgil - Nyx",
  "Virgil - Oberon",
  "Virgil - Tiber",
  "Virgil - Vega",
  "Virgil III",
  "Virgo (star)",
  "Vision Center",
  "Vivere OLP",
  "Vivere PAF-I",
  "Vivere PAF-II",
  "Vivere PAF-III",
  "Volt (star)",
  "Voodoo (star)",
  "Vosca",
  "Voyager Bar",
  "Vulture (star)",
  "Vulture - Orion",
  "Vuur",

  // === W LOCATIONS ===
  "Wailing Rock",
  "Wala",
  "Walleye",
  "Wally's",
  "Washout",
  "Watcher's Depot",
  "Weeping Cove",
  "Wheeler's",
  "Whistlers Crypt",
  "Wikelo Emporium Dasi Station",
  "Wikelo Emporium Kinga Station",
  "Wikelo Emporium Selo Station",
  "Wiley Flats",
  "Windfall",
  "Wolf Point Aid Shelter",
  "World's End",

  // === X LOCATIONS ===
  "Xenia",
  "Xi",
  "Xis",
  "Xyeping",
  "Xōl'uu",

  // === Y LOCATIONS ===
  "Y.ōm'e",
  "Yadar Valley",
  "Yang's Place",
  "Yar",
  "Ye'ten",
  "Ye'ton",
  "Yela",
  "Yengchuai",
  "Yethlūl S.yen'o",
  "Yethlūl Y.ath'o",
  "Yogi Station",
  "Yulin (star)",
  "Yulin - Banshee",
  "Yulin - Leir",
  "Yulin Cluster Alpha",
  "Yulin Flotilla",
  "Yulin I",
  "Yulin II",
  "Yulin III",
  "Yulin IV",
  "Yulin V",
  "Yulin VI",
  "Yā'mon (star)",
  "Yā'mon - Ail'ka",
  "Yā'mon - Baker",
  "Yā'ti",
  "Yām'ping",
  "Yā'mon Belt Alpha",

  // === Z LOCATIONS ===
  "Zephyr (settlement)"
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { locations };
}
